version: '3.8'

services:
  webapp:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - SECRET_KEY=your-secret-key-here
    volumes:
      - ../webapp:/app 